services:
  - type: web
    name: my-strapi-app
    env: node
    plan: free
    buildCommand: |
      echo "=== Strapi Build with npm ==="
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      echo "Installing dependencies..."
      npm ci --only=production
      echo "Installing sharp for Linux..."
      npm install --os=linux --cpu=x64 sharp
      echo "Disabling SWC compiler and building admin panel..."
      export STRAPI_DISABLE_SWC=true
      export NODE_OPTIONS="--max-old-space-size=4096"
      echo "Building Strapi application with admin panel..."
      STRAPI_DISABLE_SWC=true npm run build:admin
      echo "Verifying admin panel build..."
      ls -la node_modules/@strapi/admin/dist/server/server/build/ || echo "Admin panel build directory not found"
      echo "Build completed!"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: sqlite
      - key: DATABASE_FILENAME
        value: .tmp/data.db
      - key: NODE_VERSION
        value: "20"
      - key: STRAPI_DISABLE_UPLOAD
        value: "true"
      - key: STRAPI_DISABLE_SWC
        value: "true"
      - key: STRAPI_TELEMETRY_DISABLED
        value: "true"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
      - key: STRAPI_UPLOAD_PROVIDER
        value: "local"
      - key: STRAPI_UPLOAD_PROVIDER_OPTIONS
        value: "{}"
      - key: STRAPI_ADMIN_PATH
        value: "/admin"
      - key: STRAPI_ADMIN_BACKEND_URL
        value: "https://my-strapi-app-uaeb.onrender.com" 