services:
  - type: web
    name: my-strapi-app
    env: node
    plan: free
    buildCommand: |
      echo "=== Strapi Build with npm ==="
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      echo "Installing dependencies..."
      npm ci --only=production
      echo "Disabling SWC compiler..."
      export STRAPI_DISABLE_SWC=true
      export NODE_OPTIONS="--max-old-space-size=4096"
      echo "Building Strapi application..."
      STRAPI_DISABLE_SWC=true npm run build
      echo "Build completed!"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: sqlite
      - key: DATABASE_FILENAME
        value: .tmp/data.db
      - key: NODE_VERSION
        value: "20"
      - key: STRAPI_DISABLE_UPLOAD
        value: "true"
      - key: STRAPI_DISABLE_SWC
        value: "true"
      - key: STRAPI_TELEMETRY_DISABLED
        value: "true"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096" 