services:
  - type: web
    name: my-strapi-app
    env: node
    plan: free
    buildCommand: chmod +x .render-build.sh && ./.render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: sqlite
      - key: DATABASE_FILENAME
        value: .tmp/data.db
      - key: NPM_CONFIG_PACKAGE_LOCK_ONLY
        value: "true" 