services:
  - type: web
    name: my-strapi-app
    env: node
    plan: free
    buildCommand: |
      echo "=== Strapi Build with npm ==="
      echo "Node version: $(node --version)"
      echo "NPM version: $(npm --version)"
      echo "Installing dependencies..."
      npm ci --only=production
      echo "Installing sharp for Linux..."
      npm install --include=optional sharp
      echo "Building Strapi application..."
      npm run build
      echo "Build completed!"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: sqlite
      - key: DATABASE_FILENAME
        value: .tmp/data.db
      - key: NODE_VERSION
        value: "20"
      - key: SHARP_IGNORE_GLOBAL_LIBVIPS
        value: "1"
      - key: NPM_CONFIG_PLATFORM
        value: "linux"
      - key: NPM_CONFIG_ARCH
        value: "x64" 